version: '3.8'
services:
  db:
    image: postgres:17
    container_name: springboot_postgres_db
    environment:
      POSTGRES_USER: paulinchi
      POSTGRES_PASSWORD: paulinchi
      POSTGRES_DB: magic_bd
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - springboot_network

volumes:
  postgres_data:

networks:
  springboot_network:
