spring:
  datasource:
    url: jdbc:h2:mem:Magic  # Configuración de base de datos en memoria para pruebas
    username: pcalvo
    password: pcalvo
    driver-class-name:  org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  test:
    enabled: true
  profiles:
    active: test
